"""Initial migration

Revision ID: 3247fcc45345
Revises: 
Create Date: 2023-11-05 20:02:46.605737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3247fcc45345'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('money', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=12),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('money', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.String(length=12),
               type_=sa.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
